In [1]:
import numpy as np

# Numpy

**Bold**

*Italic*

> quote

1. order list

- unordered

'code'

# Array Creation

In [ ]:
arr=np.array([1,2,3]) #1d array
arr[2]  #return output with dtype like np.int64(indexing_element)

In [ ]:
arr1=np.array([[1,2,3],[4,5,6]],np.int32) #can also pass data type while making array   #2d array
arr1[1,2]
arr1.shape #row,column
arr1.size# number of elements
arr1.dtype #data type
arr1[0,2]=56 #updating element of array
arr1

In [ ]:
arr1=np.array([[[1,2,3],[4,5,6]]]) #3d array
arr1[0,1,2]
arr1.shape

**Creation from other structures**

In [ ]:
list1=[[1,2,3,3],[4,5,6,6]]
arr2=np.array(list1) #converting list into array
arr2.shape
arr2

In [ ]:
dict1={1,2,3,4,4}  #remove duplicate bcz we are passing set
arr3=np.array(dict1)
arr3.dtype #dtype object ('O')

In [ ]:
dict1 = {"apple": 3, "banana": 5, "orange": 2}
arr_values = np.array(list(dict1.values()))
arr_values.dtype
#we can also convert dictionary to array
# use dict1.values to converting only for values
# use dict1.keys to converting only for keys 


**Intrinsic creation of array**

In [ ]:
# zero=np.zeros(3,4) throw error bcz its second argument is for data type
zero=np.zeros((3,4),dtype="int64") #bydefault zeros function has float datatype but we can convert it into any datatype
#return 3x4 array with all zero
zero

In [ ]:
#arange function
arnge=np.arange(12)
#generate element from 0 to n-1
arnge.dtype
#we can convert 1d array to 2d array using reshape function
arnge2d=arnge.reshape(4,3)  #pass argument multiplication must be equal to length of main array 
arnge2d
arnge1d=arnge2d.ravel() #ravel used to convert any array into 1d
arnge1d

In [ ]:
#linspace function
lin=np.linspace(2,20,10,dtype="int64")
#generate 10 equally space element from 2 to 20
#distance between all consecutive element same
lin

In [ ]:
#empty function
emp=np.empty((4,5)) #generate random values
emp

In [ ]:
#empty_like
emp1=np.empty_like((emp)) #create an array of same data type and same shape with random values
emp1

In [ ]:
#identity matrix
iden=np.identity(4) #create 4x4 matrix where primary diagonal is 1
iden

In [ ]:
ar1=np.arange(2,20,3) 
#generate element from 2 to 20 with gap of 3
ar1

**Numpy axis**

In [ ]:
# 1d array contains only axis 0
#2d array contains axis 0(down column) and axis 1(across rows)
#axis will be used in some function
arr1=np.arange(12)
arr2=arr1.reshape(3,4)
print(arr2)
arr2.sum(axis=0)  #sum all element column wise
arr2.sum(axis=1) #sum all element row wise

In [ ]:
#transpose of array (T)
arr2.T

In [ ]:
arr2.ndim  #dimension 2d 3d 1d
arr2.flat #used to iterate throughout the array
print(arr2)
for i in arr2.flat: #iterate through row wise
    print(i)

In [ ]:
arr2.nbytes #total number of bytes consumed by array

In [ ]:
#argmin argmax argsort for 1d
a1=np.array([5,6,8,9,0,2])
a1.argmax()  #return index of maximum
a1.argmin()  #return index of minimum
a1.argsort() #return indices of sorting element in increasing order
#ex: 20,40,0  return 2,0,1 bcz at 2nd indices smallest element

In [146]:
#argmin argmax argsort for 2d
a1=np.array([5,6,8,9,0,20])
a2=a1.reshape(3,2)
a2
a2.argmax()#first convert into 1d then return indices
a2.argmin() #convert into 1d then return indices
a2.argsort()
a2

None


array([[ 5,  6],
       [ 8,  9],
       [ 0, 20]])

In [ ]:
print(a2)
a2.argmax(axis=0) #return columnwise max value indices
a2.argmin(axis=1) #return rowwise min value indices
a2.argsort(axis=0) #return indices columnwise sorting

In [150]:
a11=np.arange(1,10)
ah=np.sort(a11)[::-1] #sort array in descending order
print(ah)
a12=np.arange(0,9)
a11+a12  #add index wise
a11*a12  #multi index wise
a12-a11

[9 8 7 6 5 4 3 2 1]


array([-1, -1, -1, -1, -1, -1, -1, -1, -1])

In [ ]:
#square root
np.sqrt(a11)  #return square root of every element
a13=a11.reshape(3,3)
a13.sum()  # return sum of all element of array
a13.max()
a13.min()

In [ ]:
#finding element from array
print(a13)
a13.shape
np.where(a13>6)
# return two array first of row indices and second one of column indices
type(np.where(a13>6))  #return type tuple of two array

In [ ]:
#count non-zero
np.count_nonzero(a13) #return count of non zero value
np.nonzero(a13)  #return two array one of row and other one of column indices where element is not zero

In [135]:
#checking how numpy array takes less memory than python list/array
import sys

In [137]:
py_arr=[5,8,7,9]
np_arr=np.array(py_arr)

In [ ]:
sys.getsizeof(1)*len(py_arr)  #memory taken by python array/list

In [ ]:
np_arr.itemsize*len(np_arr)  #memory taken by numpy array

In [143]:
#array to list
np_arr.tolist()

[5, 8, 7, 9]

In [ ]:
# The sys library in Python provides access to variables and functions that interact closely with the Python runtime environment